version: '3'

services:
  mq-container:
    image: breznadam/mq-container
    ports:
      - "61616:61616"
      - "8161:8161"
    container_name: mq-container
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://mq-container:8161"]
      interval: 3s
      timeout: 10s
      retries: 3

  crawler:
    image: ricardocardn/crawler
    ports:
      - "80:80"
    volumes:
      - /home/ricardocardenes12/DocumentRepository:/app/DocumentsRepository
    depends_on:
      mq-container:
        condition: service_healthy