version: '3'

services:
  mongodb-container:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongobd-container
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      retries: 3


  user-service:
    image: ricardocardn/user-service
    ports:
      - "80:8080"
    environment:
      SERVER_MQ_PORT: 443
      SERVER_API_URL: http://34.16.187.84
    depends_on:
      mongodb-container:
        condition: service_healthy